use serde::{Deserialize, Serialize};
use time::OffsetDateTime;
use uuid::Uuid;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AccountId(pub String);

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MessageId(pub String);

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MailAddress {
    pub display_name: Option<String>,
    pub address: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HeaderAuth {
    pub spf: AuthResult,
    pub dkim: AuthResult,
    pub dmarc: AuthResult,
    pub arc: AuthResult,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum AuthResult {
    Pass,
    Fail,
    SoftFail,
    Neutral,
    None,
    Unknown(String),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MessageEnvelope {
    pub account_id: AccountId,
    pub message_id: MessageId,
    pub thread_id: Option<String>,
    pub from: MailAddress,
    pub reply_to: Option<MailAddress>,
    pub to: Vec<MailAddress>,
    pub cc: Vec<MailAddress>,
    pub subject: String,
    pub received_at: OffsetDateTime,
    pub auth: HeaderAuth,
    pub plain_text: Option<String>,
    /// Raw HTML is quarantined data. Trusted UI must never receive this field.
    pub raw_html: Option<Vec<u8>>,
    pub links: Vec<ObservedLink>,
    pub attachments: Vec<AttachmentDescriptor>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ObservedLink {
    pub visible_text: String,
    pub raw_target: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttachmentDescriptor {
    pub id: String,
    pub file_name: Option<String>,
    pub declared_mime: Option<String>,
    pub size_bytes: u64,
    pub sha256: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RiskSignal {
    pub code: String,
    pub severity: Severity,
    pub title: String,
    pub explanation: String,
    pub evidence: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Severity {
    Info,
    Low,
    Medium,
    High,
    Critical,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RiskReport {
    pub report_id: Uuid,
    pub message_id: MessageId,
    pub score: u8,
    pub signals: Vec<RiskSignal>,
    pub generated_at: OffsetDateTime,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SafeDocument {
    pub subject: String,
    pub sender_display: String,
    pub plain_blocks: Vec<String>,
    pub links: Vec<SafeLink>,
    pub images: Vec<SafeImageRef>,
    pub warnings: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SafeLink {
    pub label: String,
    pub scheme: String,
    pub host_ascii: String,
    pub host_display: String,
    pub path: String,
    pub clickable: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SafeImageRef {
    /// Points only to a locally re-encoded image generated by the safe-render worker.
    pub local_id: String,
    pub width: u32,
    pub height: u32,
}
