import type { MailItem, NavKey } from "../types";

export function DashboardView({view,messages}:{view:NavKey,messages:MailItem[]}) {
  const risky=messages.filter(m=>m.riskScore>=30);
  if(view==="security") return <div className="dashboard"><p className="eyebrow">SECURITY CENTER</p><h1>Signals, not blind trust.</h1><div className="metricGrid"><Metric v={risky.length} l="Messages with signals"/><Metric v={messages.filter(m=>m.riskScore>=70).length} l="High risk"/><Metric v="0" l="Remote images loaded"/></div><h2>Current signals</h2>{risky.flatMap(m=>m.signals.map(s=><div className="dashRow" key={m.id+s.code}><strong>{s.title}</strong><span>{m.subject}</span><em>{s.severity}</em></div>))}</div>;
  if(view==="cleanup") return <div className="dashboard"><p className="eyebrow">CLEANUP PLAN</p><h1>Reduce noise without irreversible automation.</h1><div className="metricGrid"><Metric v="18" l="Suggested archive"/><Metric v="3" l="Newsletter groups"/><Metric v="0" l="Permanent deletes"/></div><div className="proposal"><strong>Suggested: archive recurring newsletters older than 30 days</strong><p>Preview first. Provider state is not changed by this local demo.</p><button className="primary">Review 18 messages</button></div></div>;
  if(view==="quarantine") return <div className="dashboard"><p className="eyebrow">QUARANTINE</p><h1>Content held outside trusted view.</h1>{messages.filter(m=>m.quarantined).map(m=><div className="proposal" key={m.id}><strong>{m.subject}</strong><p>{m.senderAddress}</p><button>Inspect metadata</button></div>)}</div>;
  if(view==="accounts") return <div className="dashboard"><p className="eyebrow">ACCOUNT HUB</p><h1>Providers connect to one local security pipeline.</h1><div className="accountCards"><Account name="Google / Gmail" state="Not connected"/><Account name="Microsoft 365 / Outlook" state="Not connected"/><Account name="IMAP / SMTP" state="Planned"/></div></div>;
  if(view==="rules") return <div className="dashboard"><p className="eyebrow">RULES</p><h1>Automation must remain reversible.</h1><div className="proposal"><strong>Security invariant</strong><p>Rules can label, archive, quarantine or move to trash. They cannot permanently delete.</p></div></div>;
  if(view==="productivity") return <div className="dashboard"><p className="eyebrow">PRODUCTIVITY</p><h1>Mail operations without another tracking cloud.</h1><div className="metricGrid"><Metric v="Soon" l="Send later"/><Metric v="Soon" l="Snooze"/><Metric v="Soon" l="Templates"/></div></div>;
  return <div className="dashboard"><p className="eyebrow">SETTINGS</p><h1>Local-first defaults.</h1><div className="setting"><span>Remote images</span><strong>Blocked</strong></div><div className="setting"><span>Telemetry</span><strong>Off</strong></div><div className="setting"><span>Permanent-delete rules</span><strong>Disabled</strong></div></div>;
}
function Metric({v,l}:{v:string|number,l:string}){return <div className="metric"><strong>{v}</strong><span>{l}</span></div>}
function Account({name,state}:{name:string,state:string}){return <article className="account"><div><strong>{name}</strong><small>{state}</small></div><button>Connect</button></article>}
